server:
  port: 8087
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mobilesubscriberdb?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: username
    password: password
    max-active: 500
    initial-size: 100
    max-idle: 1
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: validate
    properties:
      hibernate.show_sql: false
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect 
 